export default {
  profile: "Profile",
  logout: "Logout",
  login: "Login",
  email: "Email",
  password: "Password",
  passwordChange: "Password change",
  newPassword: "New password",
  confirmPassword: "Confirm new password",
  remember: "Remember",
  forgot: "Forgot your password?",
  register: "Register",
  name: "Name",
  lastname: "Last name",
  phone: "Phone",
  address: "Address",
  city: "City",
  country: "Country",
  postal: "Postal code",
  registerButton: "Register",
  loginButton: "Login",
  logoutButton: "Logout",
  profileButton: "Profile",
  homeButton: "Home",
  save: "Save",
  welcome: "Welcome",
  username: "User",
  personalInfo: "Personal data",

  deleteStoredData: "Would you like to delete all stored data?",
  loginOut: "Logging out ...",

  dark: "Dark",
  light: "Light",

  selectColorMode: "Choose color mode",
  selectLanguage: "Choose language",
  usedStorageSize: "Used storage size",

  settings: "Settings",
  help: "Help",
  about: "About",
  home: "Home",

  version: "Version",
};
