export default {
  profile: "Perfil",
  logout: "Cerrar Sesión",
  login: "Iniciar Sesión",
  email: "Correo Electrónico",
  password: "Contraseña",
  passwordChange: "Cambiar Contraseña",
  newPassword: "Nueva contraseña",
  confirmPassword: "Confirmar nueva contraseña",
  remember: "Recordar",
  forgot: "¿Olvidaste tu contraseña?",
  register: "Registrarse",
  name: "Nombre",
  lastname: "Apellido",
  phone: "Teléfono",
  address: "Dirección",
  city: "Ciudad",
  country: "País",
  postal: "Código Postal",
  registerButton: "Registrarse",
  loginButton: "Iniciar Sesión",
  logoutButton: "Cerrar Sesión",
  profileButton: "Perfil",
  homeButton: "Inicio",
  save: "Guardar",
  welcome: "Bienvenid@",
  username: "Usuario",
  personalInfo: "Datos personales",

  deleteStoredData: "¿Desea eliminar todos los datos almacenados?",
  loginOut: "Cerrando sesión ...",

  dark: "Oscuro",
  light: "Claro",

  selectColorMode: "Seleccione el modo de color",
  selectLanguage: "Seleccione el idioma",
  usedStorageSize: "Tamaño de almacenamiento utilizado",

  settings: "Configuración",
  help: "Ayuda",
  about: "Acerca de",
  home: "Inicio",

  version: "Versión",
};
